In [40]:
from pathlib import Path
import pandas as pd
import json

data_path = Path("data")

df = pd.read_csv(data_path / "base_data.csv")

with open(data_path / "csv_dictionary.json") as f:
    raw = json.load(f)

CSVDictionary = {
    k: pd.DataFrame(v)
    for k, v in raw.items()
}

In [30]:
df.head()

,id,url,fullName,parkCode,description,latitude,longitude,latLong,activities,topics,...,operatingHours,addresses,images,weatherInfo,name,designation,multimedia,relevanceScore,contacts.phoneNumbers,contacts.emailAddresses
0,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,"[{'exceptions': [], 'description': 'Acadia Nat...","[{'postalCode': '04609', 'city': 'Bar Harbor',...","[{'credit': 'NPS / Kristi Rugg', 'title': 'Sun...","Located on Mount Desert Island in Maine, Acadi...",Acadia,National Park,"[{'title': 'Cultural Connections in the Park',...",1.0,"[{'phoneNumber': '2072883338', 'description': ...","[{'description': '', 'emailAddress': 'acadia_i..."
1,36240051-018E-4915-B6EA-3F1A7F24FBE4,https://www.nps.gov/arch/index.htm,Arches National Park,arch,"Discover a landscape of contrasting colors, la...",38.722618,-109.586367,"lat:38.72261844, long:-109.5863666",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B'...,...,"[{'exceptions': [], 'description': 'Arches Nat...","[{'postalCode': '84532', 'city': 'Moab', 'stat...","[{'credit': 'NPS/Veronica Verdin', 'title': 'A...","Arches is part of the Colorado Plateau, a ""hig...",Arches,National Park,[],1.0,"[{'phoneNumber': '4357192299', 'description': ...","[{'description': '', 'emailAddress': 'archinfo..."
2,B170CCF7-7AB9-48FF-950E-31815FD4DBB2,https://www.nps.gov/badl/index.htm,Badlands National Park,badl,The rugged beauty of the Badlands draws visito...,43.685848,-102.482942,"lat:43.68584846, long:-102.482942",[{'id': '5F723BAD-7359-48FC-98FA-631592256E35'...,[{'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B'...,...,"[{'exceptions': [], 'description': 'The park i...","[{'postalCode': '57750', 'city': 'Interior', '...","[{'credit': 'NPS Photo', 'title': 'Badlands St...",The Badlands weather is variable and unpredict...,Badlands,National Park,[],1.0,"[{'phoneNumber': '6054335361', 'description': ...","[{'description': '', 'emailAddress': 'badl_inf..."
3,C9056F71-7162-4208-8AE9-2D0AEFA594FD,https://www.nps.gov/bibe/index.htm,Big Bend National Park,bibe,There is a place in Far West Texas where night...,29.298178,-103.229790,"lat:29.29817767, long:-103.2297897",[{'id': '5F723BAD-7359-48FC-98FA-631592256E35'...,[{'id': '7F81A0CB-B91F-4896-B9A5-41BE9A54A27B'...,...,"[{'exceptions': [], 'description': 'Big Bend N...","[{'postalCode': '79834', 'city': 'Big Bend Nat...","[{'credit': 'NPS', 'title': 'Blooming Cenizo',...",Big Bend is in the Chihuahuan Desert. Sunshine...,Big Bend,National Park,[],1.0,"[{'phoneNumber': '432-477-2251', 'description'...","[{'description': '', 'emailAddress': 'bibe_inf..."
4,FBF9F793-5114-4B61-A5BA-6F9ADDFDF459,https://www.nps.gov/bisc/index.htm,Biscayne National Park,bisc,"Within sight of Miami, yet worlds away, Biscay...",25.490587,-80.210239,"lat:25.490587, long:-80.21023851",[{'id': '071BA73C-1D3C-46D4-A53C-00D5602F7F0E'...,[{'id': '28AEAE85-9DDA-45B6-981B-1CFCDCC61E14'...,...,"[{'exceptions': [], 'description': 'Launch you...","[{'postalCode': '33033', 'city': 'Homestead', ...","[{'credit': 'NPS image by Shaun Wolfe', 'title...","The park is situated in a subtropical climate,...",Biscayne,National Park,[],1.0,"[{'phoneNumber': '786-335-3620', 'description'...","[{'description': ""If you can't find what you a..."

In [31]:
CSVDictionary.keys()

dict_keys(['ACAD', 'ARCH', 'BADL', 'BIBE', 'BISC', 'BLCA', 'BRCA', 'CANY', 'CARE', 'CAVE', 'CHIS', 'CONG', 'CRLA', 'CUVA', 'DEVA', 'DENA', 'DRTO', 'EVER', 'GAAR', 'JEFF', 'GLBA', 'GLAC', 'GRCA', 'GRTE', 'GRBA', 'GRSA', 'GRSM', 'GUMO', 'HALE', 'HAVO', 'HOSP', 'INDU', 'ISRO', 'JOTR', 'KATM', 'KEFJ', 'KOVA', 'LACL', 'LAVO', 'MACA', 'MEVE', 'MORA', 'NPSA', 'NERI', 'NOCA', 'OLYM', 'PEFO', 'PINN', 'ROMO', 'SAGU', 'SHEN', 'THRO', 'VIIS', 'VOYA', 'WHSA', 'WICA', 'WOTR', 'WRST', 'YELL', 'YOSE', 'ZION'])

In [33]:
print(CSVDictionary.get("ACAD", "Key not found"))
CSVDictionary["ACAD"].shape

     Year  RecreationVisitors TotalRecreationVisitors
0    1919               64000             196,625,585
1    1920               66500             196,625,585
2    1921               69836             196,625,585
3    1922               73779             196,625,585
4    1923               64200             196,625,585
..    ...                 ...                     ...
102  2021             4069098             196,625,585
103  2022             3970260             196,625,585
104  2023             3879890             196,625,585
105  2024             3961661             196,625,585
106  2025             4079318             196,625,585

[107 rows x 3 columns]

(107, 3)

In [34]:
#TESTING BUG

print(df.columns.tolist())

['id', 'url', 'fullName', 'parkCode', 'description', 'latitude', 'longitude', 'latLong', 'activities', 'topics', 'states', 'entranceFees', 'entrancePasses', 'fees', 'directionsInfo', 'directionsUrl', 'operatingHours', 'addresses', 'images', 'weatherInfo', 'name', 'designation', 'multimedia', 'relevanceScore', 'contacts.phoneNumbers', 'contacts.emailAddresses']

In [41]:
import pandas as pd
import json

# Load base_data.csv
base_df = pd.read_csv(data_path/'base_data.csv')

#When was the "base_data.csv" file created?

# Load csv_dictionary.json
with open(data_path/'csv_dictionary.json', 'r') as f:
    csv_dict = json.load(f)

#Do we need this line? The csv was already loaded in the first block

# Prepare a list to collect new rows
rows = []

# For each park in the dictionary
for park_code, records in csv_dict.items():
    for record in records:
        row = base_df[base_df['parkCode'].str.lower() == park_code.lower()].copy()
        if not row.empty:
            row = row.iloc[0].to_dict()
            row['year'] = record['Year']
            row['annual visits'] = record['RecreationVisitors']
            row['total visits'] = record.get('TotalRecreationVisitors', None)
            rows.append(row)

# Create the new DataFrame
combined_df = pd.DataFrame(rows)
combined_df.head()

,id,url,fullName,parkCode,description,latitude,longitude,latLong,activities,topics,...,weatherInfo,name,designation,multimedia,relevanceScore,contacts.phoneNumbers,contacts.emailAddresses,year,annual visits,total visits
0,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,"Located on Mount Desert Island in Maine, Acadi...",Acadia,National Park,"[{'title': 'Cultural Connections in the Park',...",1.0,"[{'phoneNumber': '2072883338', 'description': ...","[{'description': '', 'emailAddress': 'acadia_i...",1919,64000,"196,625,585"
1,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,"Located on Mount Desert Island in Maine, Acadi...",Acadia,National Park,"[{'title': 'Cultural Connections in the Park',...",1.0,"[{'phoneNumber': '2072883338', 'description': ...","[{'description': '', 'emailAddress': 'acadia_i...",1920,66500,"196,625,585"
2,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,"Located on Mount Desert Island in Maine, Acadi...",Acadia,National Park,"[{'title': 'Cultural Connections in the Park',...",1.0,"[{'phoneNumber': '2072883338', 'description': ...","[{'description': '', 'emailAddress': 'acadia_i...",1921,69836,"196,625,585"
3,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,"Located on Mount Desert Island in Maine, Acadi...",Acadia,National Park,"[{'title': 'Cultural Connections in the Park',...",1.0,"[{'phoneNumber': '2072883338', 'description': ...","[{'description': '', 'emailAddress': 'acadia_i...",1922,73779,"196,625,585"
4,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,"Located on Mount Desert Island in Maine, Acadi...",Acadia,National Park,"[{'title': 'Cultural Connections in the Park',...",1.0,"[{'phoneNumber': '2072883338', 'description': ...","[{'description': '', 'emailAddress': 'acadia_i...",1923,64200,"196,625,585"

In [ ]:
# Build a set of activities from all unique park codes in combined_df

activities = set()
import re

for code in combined_df['parkCode'].unique():
    park_rows = combined_df[combined_df['parkCode'] == code]
    for row_activities in park_rows['activities']:
        if isinstance(row_activities, str):
            matches = re.findall(r':\s*([^,;]+)', row_activities)
            for activity in matches:
                cleaned = re.sub(r'[^A-Za-z\s]', '', activity)
                cleaned = cleaned.strip()
                if cleaned and cleaned[0].isupper() and not cleaned.isupper():
                    activities.add(cleaned.lower())
print(activities)

{'canyoneering', 'swimming', 'birdwatching', 'boat tour', 'motorized boating', 'downhill skiing', 'gathering and foraging', 'scuba diving', 'junior ranger program', 'scenic driving', 'horse camping see also camping', 'geocaching', 'mountain climbing', 'busshuttle guided tour', 'park film', 'atv offroading', 'arts and crafts', 'wildlife watching', 'fixed wing flying', 'ice skating', 'food', 'caving', 'horse trekking', 'tubing', 'boating', 'orienteering', 'snowshoeing', 'selfguided tours  auto', 'astronomy', 'crosscountry skiing', 'reenactments', 'gift shop and souvenirs', 'skiing', 'bookstore and park store', 'craft demonstrations', 'shopping', 'first person interpretation', 'rv camping', 'picnicking', 'offtrail permitted hiking', 'dining', 'whitewater rafting', 'hunting', 'rock climbing', 'snow play', 'car or front country camping', 'backcountry hiking', 'snorkeling', 'flying', 'arts and culture', 'horse camping see also horsestock use', 'paddling', 'camping', 'backcountry camping', 'snow tubing', 'compass and gps', 'canoe or kayak camping', 'frontcountry hiking', 'playground', 'stargazing', 'freshwater swimming', 'helicopter flying', 'snowmobiling', 'dog sledding', 'handson', 'hunting and gathering', 'river tubing', 'stand up paddleboarding', 'surfing', 'water skiing', 'climbing', 'cultural demonstrations', 'kayaking', 'auto and atv', 'guided tours', 'volunteer vacation', 'golf', 'theater', 'road biking', 'fishing', 'selfguided tours  walking', 'museum exhibits', 'mountain biking', 'pool swimming', 'sailing', 'hiking', 'biking', 'saltwater fishing', 'citizen science', 'ice climbing', 'horseback riding', 'historic weapons demonstration', 'fly fishing', 'group camping', 'saltwater swimming', 'canoeing', 'auto offroading', 'live music', 'living history', 'freshwater fishing'}

In [37]:
# Create dummy variables for each activity in the set
for activity in activities:
    col_name = f'activity_{activity.replace(" ", "_")}'
    combined_df[col_name] = combined_df['activities'].apply(lambda x: 1 if isinstance(x, str) and activity in x.lower() else 0)
combined_df.head()

C:\Users\Gunnar Griffith\AppData\Local\Temp\ipykernel_2664\1166237519.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_df[col_name] = combined_df['activities'].apply(lambda x: 1 if isinstance(x, str) and activity in x.lower() else 0)
C:\Users\Gunnar Griffith\AppData\Local\Temp\ipykernel_2664\1166237519.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_df[col_name] = combined_df['activities'].apply(lambda x: 1 if isinstance(x, str) and activity in x.lower() else 0)

,id,url,fullName,parkCode,description,latitude,longitude,latLong,activities,topics,...,activity_horseback_riding,activity_historic_weapons_demonstration,activity_fly_fishing,activity_group_camping,activity_saltwater_swimming,activity_canoeing,activity_auto_offroading,activity_live_music,activity_living_history,activity_freshwater_fishing
0,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,1,0,1,1,1,1,0,0,0,1
1,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,1,0,1,1,1,1,0,0,0,1
2,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,1,0,1,1,1,1,0,0,0,1
3,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,1,0,1,1,1,1,0,0,0,1
4,6DA17C86-088E-4B4D-B862-7C1BD5CF236B,https://www.nps.gov/acad/index.htm,Acadia National Park,acad,Acadia National Park protects the natural beau...,44.409286,-68.247501,"lat:44.409286, long:-68.247501",[{'id': '09DF0950-D319-4557-A57E-04CD2F63FF42'...,[{'id': '00F3C3F9-2D67-4802-81AE-CCEA5D3BA370'...,...,1,0,1,1,1,1,0,0,0,1

In [38]:
combined_df.columns

Index(['id', 'url', 'fullName', 'parkCode', 'description', 'latitude',
       'longitude', 'latLong', 'activities', 'topics',
       ...
       'activity_horseback_riding', 'activity_historic_weapons_demonstration',
       'activity_fly_fishing', 'activity_group_camping',
       'activity_saltwater_swimming', 'activity_canoeing',
       'activity_auto_offroading', 'activity_live_music',
       'activity_living_history', 'activity_freshwater_fishing'],
      dtype='str', length=129)

In [39]:
combined_df.to_csv(data_path/'final.csv', index=False)